/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpeeradminIndexRouteImport } from './routes/expeeradmin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OnboardingWalletRouteImport } from './routes/onboarding.wallet'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding.verify'
import { Route as OnboardingSignupRouteImport } from './routes/onboarding.signup'
import { Route as OnboardingLoginRouteImport } from './routes/onboarding.login'
import { Route as OnboardingKycRouteImport } from './routes/onboarding.kyc'
import { Route as OnboardingForgotPasswordRouteImport } from './routes/onboarding.forgot-password'
import { Route as OnboardingBankRouteImport } from './routes/onboarding.bank'
import { Route as ExpeeradminUsersRouteImport } from './routes/expeeradmin.users'
import { Route as ExpeeradminSettingsRouteImport } from './routes/expeeradmin.settings'
import { Route as ExpeeradminRiskRouteImport } from './routes/expeeradmin.risk'
import { Route as ExpeeradminOrdersRouteImport } from './routes/expeeradmin.orders'
import { Route as ExpeeradminMerchantsRouteImport } from './routes/expeeradmin.merchants'
import { Route as ExpeeradminKycRouteImport } from './routes/expeeradmin.kyc'
import { Route as ExpeeradminDashboardRouteImport } from './routes/expeeradmin.dashboard'
import { Route as ExpeeradminAnnouncementsRouteImport } from './routes/expeeradmin.announcements'
import { Route as ExpeeradminAdsRouteImport } from './routes/expeeradmin.ads'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppSwapRouteImport } from './routes/app.swap'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSellingRouteImport } from './routes/app.selling'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppAdsRouteImport } from './routes/app.ads'
import { Route as ExpeeradminDisputesIndexRouteImport } from './routes/expeeradmin.disputes.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as ExpeeradminDisputesIdRouteImport } from './routes/expeeradmin.disputes.$id'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsLegalRouteImport } from './routes/app.settings.legal'
import { Route as AppSettingsAppearanceRouteImport } from './routes/app.settings.appearance'
import { Route as AppSellingNewRouteImport } from './routes/app.selling.new'
import { Route as AppSellingActivityIdRouteImport } from './routes/app.selling.$activityId'
import { Route as AppOrderOrderIdRouteImport } from './routes/app.order.$orderId'
import { Route as AppAdsAdIdRouteImport } from './routes/app.ads.$adId'
import { Route as AppSellingOrdersOrderIdRouteImport } from './routes/app.selling.orders.$orderId'
import { Route as AppSellingChatActivityIdRouteImport } from './routes/app.selling.chat.$activityId'
import { Route as AppOrderNewAdIdRouteImport } from './routes/app.order.new.$adId'
import { Route as AppOrderOrderIdReviewRouteImport } from './routes/app.order.$orderId.review'
import { Route as AppOrderOrderIdProofRouteImport } from './routes/app.order.$orderId.proof'
import { Route as AppOrderOrderIdDisputeRouteImport } from './routes/app.order.$orderId.dispute'
import { Route as AppOrderOrderIdChatRouteImport } from './routes/app.order.$orderId.chat'
import { Route as ApiPublicPaymentsTossRouteImport } from './routes/api/public/payments/toss'
import { Route as ApiPublicCronIndexChainRouteImport } from './routes/api/public/cron/index-chain'
import { Route as ApiPublicCronExpireOrdersRouteImport } from './routes/api/public/cron/expire-orders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminIndexRoute = ExpeeradminIndexRouteImport.update({
  id: '/expeeradmin/',
  path: '/expeeradmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingWalletRoute = OnboardingWalletRouteImport.update({
  id: '/onboarding/wallet',
  path: '/onboarding/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/onboarding/verify',
  path: '/onboarding/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignupRoute = OnboardingSignupRouteImport.update({
  id: '/onboarding/signup',
  path: '/onboarding/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLoginRoute = OnboardingLoginRouteImport.update({
  id: '/onboarding/login',
  path: '/onboarding/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingKycRoute = OnboardingKycRouteImport.update({
  id: '/onboarding/kyc',
  path: '/onboarding/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingForgotPasswordRoute =
  OnboardingForgotPasswordRouteImport.update({
    id: '/onboarding/forgot-password',
    path: '/onboarding/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingBankRoute = OnboardingBankRouteImport.update({
  id: '/onboarding/bank',
  path: '/onboarding/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminUsersRoute = ExpeeradminUsersRouteImport.update({
  id: '/expeeradmin/users',
  path: '/expeeradmin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminSettingsRoute = ExpeeradminSettingsRouteImport.update({
  id: '/expeeradmin/settings',
  path: '/expeeradmin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminRiskRoute = ExpeeradminRiskRouteImport.update({
  id: '/expeeradmin/risk',
  path: '/expeeradmin/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminOrdersRoute = ExpeeradminOrdersRouteImport.update({
  id: '/expeeradmin/orders',
  path: '/expeeradmin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminMerchantsRoute = ExpeeradminMerchantsRouteImport.update({
  id: '/expeeradmin/merchants',
  path: '/expeeradmin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminKycRoute = ExpeeradminKycRouteImport.update({
  id: '/expeeradmin/kyc',
  path: '/expeeradmin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminDashboardRoute = ExpeeradminDashboardRouteImport.update({
  id: '/expeeradmin/dashboard',
  path: '/expeeradmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeeradminAnnouncementsRoute =
  ExpeeradminAnnouncementsRouteImport.update({
    id: '/expeeradmin/announcements',
    path: '/expeeradmin/announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpeeradminAdsRoute = ExpeeradminAdsRouteImport.update({
  id: '/expeeradmin/ads',
  path: '/expeeradmin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellingRoute = AppSellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)
const ExpeeradminDisputesIndexRoute =
  ExpeeradminDisputesIndexRouteImport.update({
    id: '/expeeradmin/disputes/',
    path: '/expeeradmin/disputes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ExpeeradminDisputesIdRoute = ExpeeradminDisputesIdRouteImport.update({
  id: '/expeeradmin/disputes/$id',
  path: '/expeeradmin/disputes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLegalRoute = AppSettingsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSellingNewRoute = AppSellingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSellingRoute,
} as any)
const AppSellingActivityIdRoute = AppSellingActivityIdRouteImport.update({
  id: '/$activityId',
  path: '/$activityId',
  getParentRoute: () => AppSellingRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsAdIdRoute = AppAdsAdIdRouteImport.update({
  id: '/$adId',
  path: '/$adId',
  getParentRoute: () => AppAdsRoute,
} as any)
const AppSellingOrdersOrderIdRoute = AppSellingOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppSellingRoute,
} as any)
const AppSellingChatActivityIdRoute =
  AppSellingChatActivityIdRouteImport.update({
    id: '/chat/$activityId',
    path: '/chat/$activityId',
    getParentRoute: () => AppSellingRoute,
  } as any)
const AppOrderNewAdIdRoute = AppOrderNewAdIdRouteImport.update({
  id: '/order/new/$adId',
  path: '/order/new/$adId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderOrderIdReviewRoute = AppOrderOrderIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppOrderOrderIdRoute,
} as any)
const AppOrderOrderIdProofRoute = AppOrderOrderIdProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => AppOrderOrderIdRoute,
} as any)
const AppOrderOrderIdDisputeRoute = AppOrderOrderIdDisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => AppOrderOrderIdRoute,
} as any)
const AppOrderOrderIdChatRoute = AppOrderOrderIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppOrderOrderIdRoute,
} as any)
const ApiPublicPaymentsTossRoute = ApiPublicPaymentsTossRouteImport.update({
  id: '/api/public/payments/toss',
  path: '/api/public/payments/toss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronIndexChainRoute = ApiPublicCronIndexChainRouteImport.update({
  id: '/api/public/cron/index-chain',
  path: '/api/public/cron/index-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronExpireOrdersRoute =
  ApiPublicCronExpireOrdersRouteImport.update({
    id: '/api/public/cron/expire-orders',
    path: '/api/public/cron/expire-orders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/ads': typeof AppAdsRouteWithChildren
  '/app/fees': typeof AppFeesRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/selling': typeof AppSellingRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/swap': typeof AppSwapRoute
  '/app/wallet': typeof AppWalletRoute
  '/expeeradmin/ads': typeof ExpeeradminAdsRoute
  '/expeeradmin/announcements': typeof ExpeeradminAnnouncementsRoute
  '/expeeradmin/dashboard': typeof ExpeeradminDashboardRoute
  '/expeeradmin/kyc': typeof ExpeeradminKycRoute
  '/expeeradmin/merchants': typeof ExpeeradminMerchantsRoute
  '/expeeradmin/orders': typeof ExpeeradminOrdersRoute
  '/expeeradmin/risk': typeof ExpeeradminRiskRoute
  '/expeeradmin/settings': typeof ExpeeradminSettingsRoute
  '/expeeradmin/users': typeof ExpeeradminUsersRoute
  '/onboarding/bank': typeof OnboardingBankRoute
  '/onboarding/forgot-password': typeof OnboardingForgotPasswordRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/app/': typeof AppIndexRoute
  '/expeeradmin/': typeof ExpeeradminIndexRoute
  '/app/ads/$adId': typeof AppAdsAdIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRouteWithChildren
  '/app/selling/$activityId': typeof AppSellingActivityIdRoute
  '/app/selling/new': typeof AppSellingNewRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/legal': typeof AppSettingsLegalRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/expeeradmin/disputes/$id': typeof ExpeeradminDisputesIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/expeeradmin/disputes/': typeof ExpeeradminDisputesIndexRoute
  '/api/public/cron/expire-orders': typeof ApiPublicCronExpireOrdersRoute
  '/api/public/cron/index-chain': typeof ApiPublicCronIndexChainRoute
  '/api/public/payments/toss': typeof ApiPublicPaymentsTossRoute
  '/app/order/$orderId/chat': typeof AppOrderOrderIdChatRoute
  '/app/order/$orderId/dispute': typeof AppOrderOrderIdDisputeRoute
  '/app/order/$orderId/proof': typeof AppOrderOrderIdProofRoute
  '/app/order/$orderId/review': typeof AppOrderOrderIdReviewRoute
  '/app/order/new/$adId': typeof AppOrderNewAdIdRoute
  '/app/selling/chat/$activityId': typeof AppSellingChatActivityIdRoute
  '/app/selling/orders/$orderId': typeof AppSellingOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/ads': typeof AppAdsRouteWithChildren
  '/app/fees': typeof AppFeesRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/selling': typeof AppSellingRouteWithChildren
  '/app/swap': typeof AppSwapRoute
  '/app/wallet': typeof AppWalletRoute
  '/expeeradmin/ads': typeof ExpeeradminAdsRoute
  '/expeeradmin/announcements': typeof ExpeeradminAnnouncementsRoute
  '/expeeradmin/dashboard': typeof ExpeeradminDashboardRoute
  '/expeeradmin/kyc': typeof ExpeeradminKycRoute
  '/expeeradmin/merchants': typeof ExpeeradminMerchantsRoute
  '/expeeradmin/orders': typeof ExpeeradminOrdersRoute
  '/expeeradmin/risk': typeof ExpeeradminRiskRoute
  '/expeeradmin/settings': typeof ExpeeradminSettingsRoute
  '/expeeradmin/users': typeof ExpeeradminUsersRoute
  '/onboarding/bank': typeof OnboardingBankRoute
  '/onboarding/forgot-password': typeof OnboardingForgotPasswordRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/app': typeof AppIndexRoute
  '/expeeradmin': typeof ExpeeradminIndexRoute
  '/app/ads/$adId': typeof AppAdsAdIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRouteWithChildren
  '/app/selling/$activityId': typeof AppSellingActivityIdRoute
  '/app/selling/new': typeof AppSellingNewRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/legal': typeof AppSettingsLegalRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/expeeradmin/disputes/$id': typeof ExpeeradminDisputesIdRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/expeeradmin/disputes': typeof ExpeeradminDisputesIndexRoute
  '/api/public/cron/expire-orders': typeof ApiPublicCronExpireOrdersRoute
  '/api/public/cron/index-chain': typeof ApiPublicCronIndexChainRoute
  '/api/public/payments/toss': typeof ApiPublicPaymentsTossRoute
  '/app/order/$orderId/chat': typeof AppOrderOrderIdChatRoute
  '/app/order/$orderId/dispute': typeof AppOrderOrderIdDisputeRoute
  '/app/order/$orderId/proof': typeof AppOrderOrderIdProofRoute
  '/app/order/$orderId/review': typeof AppOrderOrderIdReviewRoute
  '/app/order/new/$adId': typeof AppOrderNewAdIdRoute
  '/app/selling/chat/$activityId': typeof AppSellingChatActivityIdRoute
  '/app/selling/orders/$orderId': typeof AppSellingOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/ads': typeof AppAdsRouteWithChildren
  '/app/fees': typeof AppFeesRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/selling': typeof AppSellingRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/swap': typeof AppSwapRoute
  '/app/wallet': typeof AppWalletRoute
  '/expeeradmin/ads': typeof ExpeeradminAdsRoute
  '/expeeradmin/announcements': typeof ExpeeradminAnnouncementsRoute
  '/expeeradmin/dashboard': typeof ExpeeradminDashboardRoute
  '/expeeradmin/kyc': typeof ExpeeradminKycRoute
  '/expeeradmin/merchants': typeof ExpeeradminMerchantsRoute
  '/expeeradmin/orders': typeof ExpeeradminOrdersRoute
  '/expeeradmin/risk': typeof ExpeeradminRiskRoute
  '/expeeradmin/settings': typeof ExpeeradminSettingsRoute
  '/expeeradmin/users': typeof ExpeeradminUsersRoute
  '/onboarding/bank': typeof OnboardingBankRoute
  '/onboarding/forgot-password': typeof OnboardingForgotPasswordRoute
  '/onboarding/kyc': typeof OnboardingKycRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wallet': typeof OnboardingWalletRoute
  '/app/': typeof AppIndexRoute
  '/expeeradmin/': typeof ExpeeradminIndexRoute
  '/app/ads/$adId': typeof AppAdsAdIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRouteWithChildren
  '/app/selling/$activityId': typeof AppSellingActivityIdRoute
  '/app/selling/new': typeof AppSellingNewRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/legal': typeof AppSettingsLegalRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/expeeradmin/disputes/$id': typeof ExpeeradminDisputesIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/expeeradmin/disputes/': typeof ExpeeradminDisputesIndexRoute
  '/api/public/cron/expire-orders': typeof ApiPublicCronExpireOrdersRoute
  '/api/public/cron/index-chain': typeof ApiPublicCronIndexChainRoute
  '/api/public/payments/toss': typeof ApiPublicPaymentsTossRoute
  '/app/order/$orderId/chat': typeof AppOrderOrderIdChatRoute
  '/app/order/$orderId/dispute': typeof AppOrderOrderIdDisputeRoute
  '/app/order/$orderId/proof': typeof AppOrderOrderIdProofRoute
  '/app/order/$orderId/review': typeof AppOrderOrderIdReviewRoute
  '/app/order/new/$adId': typeof AppOrderNewAdIdRoute
  '/app/selling/chat/$activityId': typeof AppSellingChatActivityIdRoute
  '/app/selling/orders/$orderId': typeof AppSellingOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/reset-password'
    | '/app/ads'
    | '/app/fees'
    | '/app/market'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/selling'
    | '/app/settings'
    | '/app/swap'
    | '/app/wallet'
    | '/expeeradmin/ads'
    | '/expeeradmin/announcements'
    | '/expeeradmin/dashboard'
    | '/expeeradmin/kyc'
    | '/expeeradmin/merchants'
    | '/expeeradmin/orders'
    | '/expeeradmin/risk'
    | '/expeeradmin/settings'
    | '/expeeradmin/users'
    | '/onboarding/bank'
    | '/onboarding/forgot-password'
    | '/onboarding/kyc'
    | '/onboarding/login'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/wallet'
    | '/app/'
    | '/expeeradmin/'
    | '/app/ads/$adId'
    | '/app/order/$orderId'
    | '/app/selling/$activityId'
    | '/app/selling/new'
    | '/app/settings/appearance'
    | '/app/settings/legal'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/expeeradmin/disputes/$id'
    | '/app/settings/'
    | '/expeeradmin/disputes/'
    | '/api/public/cron/expire-orders'
    | '/api/public/cron/index-chain'
    | '/api/public/payments/toss'
    | '/app/order/$orderId/chat'
    | '/app/order/$orderId/dispute'
    | '/app/order/$orderId/proof'
    | '/app/order/$orderId/review'
    | '/app/order/new/$adId'
    | '/app/selling/chat/$activityId'
    | '/app/selling/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/app/ads'
    | '/app/fees'
    | '/app/market'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/selling'
    | '/app/swap'
    | '/app/wallet'
    | '/expeeradmin/ads'
    | '/expeeradmin/announcements'
    | '/expeeradmin/dashboard'
    | '/expeeradmin/kyc'
    | '/expeeradmin/merchants'
    | '/expeeradmin/orders'
    | '/expeeradmin/risk'
    | '/expeeradmin/settings'
    | '/expeeradmin/users'
    | '/onboarding/bank'
    | '/onboarding/forgot-password'
    | '/onboarding/kyc'
    | '/onboarding/login'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/wallet'
    | '/app'
    | '/expeeradmin'
    | '/app/ads/$adId'
    | '/app/order/$orderId'
    | '/app/selling/$activityId'
    | '/app/selling/new'
    | '/app/settings/appearance'
    | '/app/settings/legal'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/expeeradmin/disputes/$id'
    | '/app/settings'
    | '/expeeradmin/disputes'
    | '/api/public/cron/expire-orders'
    | '/api/public/cron/index-chain'
    | '/api/public/payments/toss'
    | '/app/order/$orderId/chat'
    | '/app/order/$orderId/dispute'
    | '/app/order/$orderId/proof'
    | '/app/order/$orderId/review'
    | '/app/order/new/$adId'
    | '/app/selling/chat/$activityId'
    | '/app/selling/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/reset-password'
    | '/app/ads'
    | '/app/fees'
    | '/app/market'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/selling'
    | '/app/settings'
    | '/app/swap'
    | '/app/wallet'
    | '/expeeradmin/ads'
    | '/expeeradmin/announcements'
    | '/expeeradmin/dashboard'
    | '/expeeradmin/kyc'
    | '/expeeradmin/merchants'
    | '/expeeradmin/orders'
    | '/expeeradmin/risk'
    | '/expeeradmin/settings'
    | '/expeeradmin/users'
    | '/onboarding/bank'
    | '/onboarding/forgot-password'
    | '/onboarding/kyc'
    | '/onboarding/login'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/wallet'
    | '/app/'
    | '/expeeradmin/'
    | '/app/ads/$adId'
    | '/app/order/$orderId'
    | '/app/selling/$activityId'
    | '/app/selling/new'
    | '/app/settings/appearance'
    | '/app/settings/legal'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/expeeradmin/disputes/$id'
    | '/app/settings/'
    | '/expeeradmin/disputes/'
    | '/api/public/cron/expire-orders'
    | '/api/public/cron/index-chain'
    | '/api/public/payments/toss'
    | '/app/order/$orderId/chat'
    | '/app/order/$orderId/dispute'
    | '/app/order/$orderId/proof'
    | '/app/order/$orderId/review'
    | '/app/order/new/$adId'
    | '/app/selling/chat/$activityId'
    | '/app/selling/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ExpeeradminAdsRoute: typeof ExpeeradminAdsRoute
  ExpeeradminAnnouncementsRoute: typeof ExpeeradminAnnouncementsRoute
  ExpeeradminDashboardRoute: typeof ExpeeradminDashboardRoute
  ExpeeradminKycRoute: typeof ExpeeradminKycRoute
  ExpeeradminMerchantsRoute: typeof ExpeeradminMerchantsRoute
  ExpeeradminOrdersRoute: typeof ExpeeradminOrdersRoute
  ExpeeradminRiskRoute: typeof ExpeeradminRiskRoute
  ExpeeradminSettingsRoute: typeof ExpeeradminSettingsRoute
  ExpeeradminUsersRoute: typeof ExpeeradminUsersRoute
  OnboardingBankRoute: typeof OnboardingBankRoute
  OnboardingForgotPasswordRoute: typeof OnboardingForgotPasswordRoute
  OnboardingKycRoute: typeof OnboardingKycRoute
  OnboardingLoginRoute: typeof OnboardingLoginRoute
  OnboardingSignupRoute: typeof OnboardingSignupRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingWalletRoute: typeof OnboardingWalletRoute
  ExpeeradminIndexRoute: typeof ExpeeradminIndexRoute
  ExpeeradminDisputesIdRoute: typeof ExpeeradminDisputesIdRoute
  ExpeeradminDisputesIndexRoute: typeof ExpeeradminDisputesIndexRoute
  ApiPublicCronExpireOrdersRoute: typeof ApiPublicCronExpireOrdersRoute
  ApiPublicCronIndexChainRoute: typeof ApiPublicCronIndexChainRoute
  ApiPublicPaymentsTossRoute: typeof ApiPublicPaymentsTossRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/': {
      id: '/expeeradmin/'
      path: '/expeeradmin'
      fullPath: '/expeeradmin/'
      preLoaderRoute: typeof ExpeeradminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/wallet': {
      id: '/onboarding/wallet'
      path: '/onboarding/wallet'
      fullPath: '/onboarding/wallet'
      preLoaderRoute: typeof OnboardingWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/signup': {
      id: '/onboarding/signup'
      path: '/onboarding/signup'
      fullPath: '/onboarding/signup'
      preLoaderRoute: typeof OnboardingSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/login': {
      id: '/onboarding/login'
      path: '/onboarding/login'
      fullPath: '/onboarding/login'
      preLoaderRoute: typeof OnboardingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/kyc': {
      id: '/onboarding/kyc'
      path: '/onboarding/kyc'
      fullPath: '/onboarding/kyc'
      preLoaderRoute: typeof OnboardingKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/forgot-password': {
      id: '/onboarding/forgot-password'
      path: '/onboarding/forgot-password'
      fullPath: '/onboarding/forgot-password'
      preLoaderRoute: typeof OnboardingForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/bank': {
      id: '/onboarding/bank'
      path: '/onboarding/bank'
      fullPath: '/onboarding/bank'
      preLoaderRoute: typeof OnboardingBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/users': {
      id: '/expeeradmin/users'
      path: '/expeeradmin/users'
      fullPath: '/expeeradmin/users'
      preLoaderRoute: typeof ExpeeradminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/settings': {
      id: '/expeeradmin/settings'
      path: '/expeeradmin/settings'
      fullPath: '/expeeradmin/settings'
      preLoaderRoute: typeof ExpeeradminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/risk': {
      id: '/expeeradmin/risk'
      path: '/expeeradmin/risk'
      fullPath: '/expeeradmin/risk'
      preLoaderRoute: typeof ExpeeradminRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/orders': {
      id: '/expeeradmin/orders'
      path: '/expeeradmin/orders'
      fullPath: '/expeeradmin/orders'
      preLoaderRoute: typeof ExpeeradminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/merchants': {
      id: '/expeeradmin/merchants'
      path: '/expeeradmin/merchants'
      fullPath: '/expeeradmin/merchants'
      preLoaderRoute: typeof ExpeeradminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/kyc': {
      id: '/expeeradmin/kyc'
      path: '/expeeradmin/kyc'
      fullPath: '/expeeradmin/kyc'
      preLoaderRoute: typeof ExpeeradminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/dashboard': {
      id: '/expeeradmin/dashboard'
      path: '/expeeradmin/dashboard'
      fullPath: '/expeeradmin/dashboard'
      preLoaderRoute: typeof ExpeeradminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/announcements': {
      id: '/expeeradmin/announcements'
      path: '/expeeradmin/announcements'
      fullPath: '/expeeradmin/announcements'
      preLoaderRoute: typeof ExpeeradminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeeradmin/ads': {
      id: '/expeeradmin/ads'
      path: '/expeeradmin/ads'
      fullPath: '/expeeradmin/ads'
      preLoaderRoute: typeof ExpeeradminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/swap': {
      id: '/app/swap'
      path: '/swap'
      fullPath: '/app/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/selling': {
      id: '/app/selling'
      path: '/selling'
      fullPath: '/app/selling'
      preLoaderRoute: typeof AppSellingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ads': {
      id: '/app/ads'
      path: '/ads'
      fullPath: '/app/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/expeeradmin/disputes/': {
      id: '/expeeradmin/disputes/'
      path: '/expeeradmin/disputes'
      fullPath: '/expeeradmin/disputes/'
      preLoaderRoute: typeof ExpeeradminDisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/expeeradmin/disputes/$id': {
      id: '/expeeradmin/disputes/$id'
      path: '/expeeradmin/disputes/$id'
      fullPath: '/expeeradmin/disputes/$id'
      preLoaderRoute: typeof ExpeeradminDisputesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/legal': {
      id: '/app/settings/legal'
      path: '/legal'
      fullPath: '/app/settings/legal'
      preLoaderRoute: typeof AppSettingsLegalRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/appearance': {
      id: '/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/selling/new': {
      id: '/app/selling/new'
      path: '/new'
      fullPath: '/app/selling/new'
      preLoaderRoute: typeof AppSellingNewRouteImport
      parentRoute: typeof AppSellingRoute
    }
    '/app/selling/$activityId': {
      id: '/app/selling/$activityId'
      path: '/$activityId'
      fullPath: '/app/selling/$activityId'
      preLoaderRoute: typeof AppSellingActivityIdRouteImport
      parentRoute: typeof AppSellingRoute
    }
    '/app/order/$orderId': {
      id: '/app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/app/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ads/$adId': {
      id: '/app/ads/$adId'
      path: '/$adId'
      fullPath: '/app/ads/$adId'
      preLoaderRoute: typeof AppAdsAdIdRouteImport
      parentRoute: typeof AppAdsRoute
    }
    '/app/selling/orders/$orderId': {
      id: '/app/selling/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/app/selling/orders/$orderId'
      preLoaderRoute: typeof AppSellingOrdersOrderIdRouteImport
      parentRoute: typeof AppSellingRoute
    }
    '/app/selling/chat/$activityId': {
      id: '/app/selling/chat/$activityId'
      path: '/chat/$activityId'
      fullPath: '/app/selling/chat/$activityId'
      preLoaderRoute: typeof AppSellingChatActivityIdRouteImport
      parentRoute: typeof AppSellingRoute
    }
    '/app/order/new/$adId': {
      id: '/app/order/new/$adId'
      path: '/order/new/$adId'
      fullPath: '/app/order/new/$adId'
      preLoaderRoute: typeof AppOrderNewAdIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/order/$orderId/review': {
      id: '/app/order/$orderId/review'
      path: '/review'
      fullPath: '/app/order/$orderId/review'
      preLoaderRoute: typeof AppOrderOrderIdReviewRouteImport
      parentRoute: typeof AppOrderOrderIdRoute
    }
    '/app/order/$orderId/proof': {
      id: '/app/order/$orderId/proof'
      path: '/proof'
      fullPath: '/app/order/$orderId/proof'
      preLoaderRoute: typeof AppOrderOrderIdProofRouteImport
      parentRoute: typeof AppOrderOrderIdRoute
    }
    '/app/order/$orderId/dispute': {
      id: '/app/order/$orderId/dispute'
      path: '/dispute'
      fullPath: '/app/order/$orderId/dispute'
      preLoaderRoute: typeof AppOrderOrderIdDisputeRouteImport
      parentRoute: typeof AppOrderOrderIdRoute
    }
    '/app/order/$orderId/chat': {
      id: '/app/order/$orderId/chat'
      path: '/chat'
      fullPath: '/app/order/$orderId/chat'
      preLoaderRoute: typeof AppOrderOrderIdChatRouteImport
      parentRoute: typeof AppOrderOrderIdRoute
    }
    '/api/public/payments/toss': {
      id: '/api/public/payments/toss'
      path: '/api/public/payments/toss'
      fullPath: '/api/public/payments/toss'
      preLoaderRoute: typeof ApiPublicPaymentsTossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/index-chain': {
      id: '/api/public/cron/index-chain'
      path: '/api/public/cron/index-chain'
      fullPath: '/api/public/cron/index-chain'
      preLoaderRoute: typeof ApiPublicCronIndexChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire-orders': {
      id: '/api/public/cron/expire-orders'
      path: '/api/public/cron/expire-orders'
      fullPath: '/api/public/cron/expire-orders'
      preLoaderRoute: typeof ApiPublicCronExpireOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdsRouteChildren {
  AppAdsAdIdRoute: typeof AppAdsAdIdRoute
}

const AppAdsRouteChildren: AppAdsRouteChildren = {
  AppAdsAdIdRoute: AppAdsAdIdRoute,
}

const AppAdsRouteWithChildren =
  AppAdsRoute._addFileChildren(AppAdsRouteChildren)

interface AppSellingRouteChildren {
  AppSellingActivityIdRoute: typeof AppSellingActivityIdRoute
  AppSellingNewRoute: typeof AppSellingNewRoute
  AppSellingChatActivityIdRoute: typeof AppSellingChatActivityIdRoute
  AppSellingOrdersOrderIdRoute: typeof AppSellingOrdersOrderIdRoute
}

const AppSellingRouteChildren: AppSellingRouteChildren = {
  AppSellingActivityIdRoute: AppSellingActivityIdRoute,
  AppSellingNewRoute: AppSellingNewRoute,
  AppSellingChatActivityIdRoute: AppSellingChatActivityIdRoute,
  AppSellingOrdersOrderIdRoute: AppSellingOrdersOrderIdRoute,
}

const AppSellingRouteWithChildren = AppSellingRoute._addFileChildren(
  AppSellingRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsLegalRoute: typeof AppSettingsLegalRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsLegalRoute: AppSettingsLegalRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppOrderOrderIdRouteChildren {
  AppOrderOrderIdChatRoute: typeof AppOrderOrderIdChatRoute
  AppOrderOrderIdDisputeRoute: typeof AppOrderOrderIdDisputeRoute
  AppOrderOrderIdProofRoute: typeof AppOrderOrderIdProofRoute
  AppOrderOrderIdReviewRoute: typeof AppOrderOrderIdReviewRoute
}

const AppOrderOrderIdRouteChildren: AppOrderOrderIdRouteChildren = {
  AppOrderOrderIdChatRoute: AppOrderOrderIdChatRoute,
  AppOrderOrderIdDisputeRoute: AppOrderOrderIdDisputeRoute,
  AppOrderOrderIdProofRoute: AppOrderOrderIdProofRoute,
  AppOrderOrderIdReviewRoute: AppOrderOrderIdReviewRoute,
}

const AppOrderOrderIdRouteWithChildren = AppOrderOrderIdRoute._addFileChildren(
  AppOrderOrderIdRouteChildren,
)

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRouteWithChildren
  AppFeesRoute: typeof AppFeesRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSellingRoute: typeof AppSellingRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSwapRoute: typeof AppSwapRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRouteWithChildren
  AppOrderNewAdIdRoute: typeof AppOrderNewAdIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRouteWithChildren,
  AppFeesRoute: AppFeesRoute,
  AppMarketRoute: AppMarketRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppSellingRoute: AppSellingRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSwapRoute: AppSwapRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRouteWithChildren,
  AppOrderNewAdIdRoute: AppOrderNewAdIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ExpeeradminAdsRoute: ExpeeradminAdsRoute,
  ExpeeradminAnnouncementsRoute: ExpeeradminAnnouncementsRoute,
  ExpeeradminDashboardRoute: ExpeeradminDashboardRoute,
  ExpeeradminKycRoute: ExpeeradminKycRoute,
  ExpeeradminMerchantsRoute: ExpeeradminMerchantsRoute,
  ExpeeradminOrdersRoute: ExpeeradminOrdersRoute,
  ExpeeradminRiskRoute: ExpeeradminRiskRoute,
  ExpeeradminSettingsRoute: ExpeeradminSettingsRoute,
  ExpeeradminUsersRoute: ExpeeradminUsersRoute,
  OnboardingBankRoute: OnboardingBankRoute,
  OnboardingForgotPasswordRoute: OnboardingForgotPasswordRoute,
  OnboardingKycRoute: OnboardingKycRoute,
  OnboardingLoginRoute: OnboardingLoginRoute,
  OnboardingSignupRoute: OnboardingSignupRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingWalletRoute: OnboardingWalletRoute,
  ExpeeradminIndexRoute: ExpeeradminIndexRoute,
  ExpeeradminDisputesIdRoute: ExpeeradminDisputesIdRoute,
  ExpeeradminDisputesIndexRoute: ExpeeradminDisputesIndexRoute,
  ApiPublicCronExpireOrdersRoute: ApiPublicCronExpireOrdersRoute,
  ApiPublicCronIndexChainRoute: ApiPublicCronIndexChainRoute,
  ApiPublicPaymentsTossRoute: ApiPublicPaymentsTossRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
